name: Deploy Python DDD Website to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'python-ddd-website/package.json'
    
    - name: Install dependencies
      run: |
        cd python-ddd-website
        npm ci
    
    - name: Build website
      run: |
        cd python-ddd-website
        npm run build
    
    - name: Run tests
      run: |
        cd python-ddd-website
        npm run test:ci
      continue-on-error: true
    
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./python-ddd-website/dist
        cname: python-ddd.dev
        
    - name: Deploy Preview (PR)
      if: github.event_name == 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./python-ddd-website/dist
        destination_dir: pr-${{ github.event.number }}
        
    - name: Comment PR with preview link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const pr_number = context.payload.pull_request.number;
          const preview_url = `https://${owner}.github.io/${repo}/pr-${pr_number}/`;
          
          github.rest.issues.createComment({
            owner,
            repo,
            issue_number: pr_number,
            body: `🚀 **Preview deployed successfully!**\n\n👀 Preview: ${preview_url}\n\n_This preview will be updated automatically with new commits._`
          });